Dev
monocuka/Data_Movie pull request #4
Opened 2023-09-21 22:02 UTC by monocuka

2023-09-21 22:05 UTC, santiaguf requested changes
data.spec.js contains unit tests from another project

2023-09-21 22:05 UTC, santiaguf commented on test/data.spec.js
> +import {filterData, sortData, computeState } from '../src/data.js';
This file should be empty, at least at this point

2023-10-05 03:33 UTC, santiaguf requested changes

2023-10-05 03:33 UTC, santiaguf commented on src/data.js
Remove bearer token

2023-10-05 03:39 UTC, andresbolivar07 approved these changes

2023-10-06 20:23 UTC, santiaguf approved these changes

2023-10-06 20:23 UTC, merged